// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using passman_back.Infrastructure.Data.DbContexts;

#nullable disable

namespace passman_back.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20220401070557_user-table")]
    partial class usertable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DirectoryPasscard", b =>
                {
                    b.Property<long>("ParentsId")
                        .HasColumnType("bigint")
                        .HasColumnName("parents_id");

                    b.Property<long>("PasscardsId")
                        .HasColumnType("bigint")
                        .HasColumnName("passcards_id");

                    b.HasKey("ParentsId", "PasscardsId")
                        .HasName("pk_directory_passcards_relations");

                    b.HasIndex("PasscardsId")
                        .HasDatabaseName("ix_directory_passcards_relations_passcards_id");

                    b.ToTable("directory_passcards_relations", (string)null);
                });

            modelBuilder.Entity("passman_back.Domain.Core.DbEntities.Directory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_directories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_directories_parent_id");

                    b.ToTable("directories", (string)null);
                });

            modelBuilder.Entity("passman_back.Domain.Core.DbEntities.Passcard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Login")
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_passcards");

                    b.ToTable("passcards", (string)null);
                });

            modelBuilder.Entity("passman_back.Domain.Core.DbEntities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DirectoryPasscard", b =>
                {
                    b.HasOne("passman_back.Domain.Core.DbEntities.Directory", null)
                        .WithMany()
                        .HasForeignKey("ParentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_directory_passcards_relations_directories_parents_id");

                    b.HasOne("passman_back.Domain.Core.DbEntities.Passcard", null)
                        .WithMany()
                        .HasForeignKey("PasscardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_directory_passcards_relations_passcards_passcards_id");
                });

            modelBuilder.Entity("passman_back.Domain.Core.DbEntities.Directory", b =>
                {
                    b.HasOne("passman_back.Domain.Core.DbEntities.Directory", "Parent")
                        .WithMany("Childrens")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_directories_directories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("passman_back.Domain.Core.DbEntities.Directory", b =>
                {
                    b.Navigation("Childrens");
                });
#pragma warning restore 612, 618
        }
    }
}
